/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "kava",
  "name": "Kava",
  "cosmosId": "kava_2222-10",
  "identifier": "kava",
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "evmId": null,
  "channels": {
    "evmos": {
      "channelId": "channel-117",
      "counterpartyChannelId": "channel-83"
    }
  },
  "feeToken": "ukava",
  "cosmosRest": [
    "https://rest.cosmos.directory/kava",
    "https://api-kava-ia.cosmosia.notional.ventures/",
    "https://kava-api.polkachu.com",
    "https://kava-mainnet-lcd.autostake.com:443"
  ],
  "tendermintRest": [
    "https://rpc.cosmos.directory/kava",
    "https://rpc.kava.io:443"
  ],
  "evmRest": null,
  "cosmosGRPC": [
    "https://rpc.kava.io:443"
  ],
  "tokens": [
    {
      "name": "USDT on Kava",
      "ref": "kava:USDT",
      "description": "Native USDT issued on Kava",
      "symbol": "USDT",
      "denom": "USDT",
      "sourcePrefix": "kava",
      "sourceDenom": "erc20/tether/usdt",
      "minCoinDenom": "erc20/tether/usdt",
      "category": "stablecoin",
      "tokenRepresentation": "USDT",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xB8f812B5943ab3BF941D5D4F1de90A4b326c5d8f",
      "handledByExternalUI": null,
      "listed": true,
      "coingeckoId": "tether"
    },
    {
      "category": "cosmos",
      "decimals": 6,
      "denom": "KAVA",
      "erc20Address": null,
      "handledByExternalUI": null,
      "description": "",
      "listed": false,
      "minCoinDenom": "ukava",
      "name": "KAVA",
      "ref": "kava:KAVA",
      "sourceDenom": "ukava",
      "sourcePrefix": "kava",
      "symbol": "KAVA",
      "tokenRepresentation": null,
      "coingeckoId": null,
      "type": "IBC"
    }
  ],
  "explorerUrl": "https://www.mintscan.io/kava/txs",
  "env": "mainnet"
} as const;