/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "stride",
  "name": "stride",
  "cosmosId": "stride-1",
  "identifier": "stride",
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "evmId": null,
  "channels": {
    "evmos": {
      "channelId": "channel-9",
      "counterpartyChannelId": "channel-25"
    }
  },
  "feeToken": "ustrd",
  "cosmosRest": [
    "https://rest.cosmos.directory/stride",
    "https://stride-api.polkachu.com",
    "https://stride.api.chandrastation.com",
    "https://api.stride.bh.rocks",
    "http://api-stride.nodeist.net",
    "https://stride-api.lavenderfive.com",
    "https://stride.rest.interchain.ivaldilabs.xyz",
    "https://api.stride.nodestake.top",
    "https://api-stride.d-stake.xyz"
  ],
  "tendermintRest": [
    "https://rpc.cosmos.directory/stride",
    "https://stride-rpc.polkachu.com:443"
  ],
  "evmRest": null,
  "cosmosGRPC": [
    "https://stride-rpc.polkachu.com:443"
  ],
  "evmRPC": [
    "https://stride-rpc.polkachu.com:443"
  ],
  "tokens": [
    {
      "name": "Stride Staked Stars",
      "description": "Staking derivative by Stride",
      "denom": "stSTARS",
      "sourcePrefix": "stride",
      "sourceDenom": "stustars",
      "minCoinDenom": "stustars",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xc7e56EEc629D3728fE41baCa2f6BFc502096f94E",
      "handledByExternalUI": null
    },
    {
      "name": "Stride Staked Osmo",
      "description": "Staking derivative by Stride",
      "denom": "stOSMO",
      "sourcePrefix": "stride",
      "sourceDenom": "stuosmo",
      "minCoinDenom": "stuosmo",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xD32eB974468ed767338533842D2D4Cc90B9BAb46",
      "handledByExternalUI": null
    },
    {
      "name": "Stride Staked Juno",
      "description": "Staking derivative by Stride",
      "denom": "stJUNO",
      "sourcePrefix": "stride",
      "sourceDenom": "stujuno",
      "minCoinDenom": "stujuno",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xc71aAf8e486e3F33841BB56Ca3FD2aC3fa8D29a8",
      "handledByExternalUI": null
    },
    {
      "name": "Stride Staked Inj",
      "description": "Staking derivative by Stride",
      "denom": "stINJ",
      "sourcePrefix": "stride",
      "sourceDenom": "stinj",
      "minCoinDenom": "stinj",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x786744d8B40ee154FA4a74153c4d33dF09aBf015",
      "handledByExternalUI": null
    },
    {
      "name": "Stride Staked Evmos",
      "description": "Staking derivative by Stride",
      "denom": "stEVMOS",
      "sourcePrefix": "stride",
      "sourceDenom": "staevmos",
      "minCoinDenom": "staevmos",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x2C68D1d6aB986Ff4640b51e1F14C716a076E44C4",
      "handledByExternalUI": null
    },
    {
      "name": "Stride Staked Atom",
      "description": "Staking derivative by Stride",
      "denom": "stATOM",
      "sourcePrefix": "stride",
      "sourceDenom": "stuatom",
      "minCoinDenom": "stuatom",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xB5124FA2b2cF92B2D469b249433BA1c96BDF536D",
      "handledByExternalUI": null
    },
    {
      "name": "Stride",
      "description": "The native token of Stride",
      "denom": "STRD",
      "sourcePrefix": "stride",
      "sourceDenom": "ustrd",
      "minCoinDenom": "ustrd",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x8FA78CEB7F04118Ec6d06AaC37Ca854691d8e963",
      "handledByExternalUI": null
    }
  ],
  "explorerUrl": "https://www.mintscan.io/stride/txs"
} as const;