import path from "path";
import { fileURLToPath } from "url";
export const __filename = fileURLToPath(import.meta.url);
export const __dirname = path.dirname(__filename);
export const registryDir = path.resolve(
  fileURLToPath(
    (await import.meta.resolve?.(
      "chain-token-registry/chainConfig/evmos.json"
    )) || ""
  ),
  "../.."
);

export const chainRegistryDir = path.resolve(registryDir, "chainConfig");
export const tokenRegistryDir = path.resolve(registryDir, "tokens");
export const rootDir = process.cwd();
export const chainOutDir = path.resolve(rootDir, "src/chain");
export const assetsDir = path.resolve(rootDir, "statics");

export const fileHeader = `/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the \`pnpm run build:registry\` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

`;
