name: "Build & Cache"
runs:
  using: "composite"
  steps:
    - name: Restore Turbo Cache
      id: turbo-cache-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules/.cache/turbo
        key: ${{ runner.os }}-turbo-

    - name: Build
      run: NEXT_PUBLIC_ENABLE_TESTNET=true pnpm build
      shell: bash

    - name: Save Turbo Cache
      id: turbo-cache-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./node_modules/.cache/turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('./node_modules/.cache/turbo/*.json') }}
