/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "axelar",
  "name": "Axelar",
  "cosmosId": "axelar-dojo-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.00005",
    "average": "0.00025",
    "high": "0.0004"
  },
  "nativeCurrency": "AXL",
  "currencies": [
    {
      "name": "Axelar",
      "description": "The native token of Axelar",
      "images": {
        "png": "statics/AXL.png",
        "svg": "statics/AXL.svg"
      },
      "denom": "AXL",
      "channel": "channel-21",
      "minCoinDenom": "uaxl",
      "cosmosDenom": "ibc/473351B37CC9D7BA7B247800EF04D255E442C4C9C93976E3631B190A8F3C5570",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x94c23eE865E3c963A56263d0ce2CBF5C6cE7ce2d"
    },
    {
      "name": "DAI by Axelar",
      "description": "DAI Stablecoin on Axelar",
      "images": {
        "png": "statics/axlDAI.png",
        "svg": "statics/axlDAI.svg"
      },
      "denom": "axlDAI",
      "channel": "channel-21",
      "minCoinDenom": "dai-wei",
      "cosmosDenom": "ibc/CBA4784581AD4BEF308C536A3CD44D4A940A520E61B0D1E4FB115C539F61DEE5",
      "category": "stablecoin",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x4A2a90D444DbB7163B5861b772f882BbA394Ca67",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "Pepe by Axelar",
      "description": "Pepe on Axelar",
      "images": {
        "png": "statics/axlPEPE.jpeg",
        "svg": "statics/axlPEPE.jpeg"
      },
      "denom": "axlPEPE",
      "channel": "channel-21",
      "minCoinDenom": "pepe-wei",
      "cosmosDenom": "ibc/26E6508A1757E12B15A087E951F5D35E73CF036F0D97BC809E1598D1DD870BED",
      "category": "ethereum",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0xc76A204AEA61a68a3B1f97B8E70286CD42B020D2",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "Rocket Pool staked ETH by Axelar",
      "description": "Rocket Pool staking derivative rETH for staked ETH on Axelar",
      "images": {
        "png": "statics/axlRETH.png",
        "svg": "statics/axlRETH.png"
      },
      "denom": "axlRETH",
      "channel": "channel-21",
      "minCoinDenom": "reth-wei",
      "cosmosDenom": "ibc/6A3538834873D16F00D0268B295A8D6FD9B005952787AA14726D0013A51042AC",
      "category": "ethereum",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0xE60CE2dfa6D4Ad37Ade1dcB7aC4D6C3A093b3A7E",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "USD Coin by Axelar",
      "description": "Circle's stablecoin on Axelar",
      "images": {
        "png": "statics/axlUSDC.png",
        "svg": "statics/axlUSDC.svg"
      },
      "denom": "axlUSDC",
      "channel": "channel-21",
      "minCoinDenom": "uusdc",
      "cosmosDenom": "ibc/63C53CBDF471D4E867366ABE2E631197257118D1B2BEAD1946C8A408F96464C3",
      "category": "stablecoin",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x15C3Eb3B621d1Bff62CbA1c9536B7c1AE9149b57",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "USDT by Axelar",
      "description": "USD Tether Stablecoin on Axelar",
      "images": {
        "png": "statics/axlUSDT.png",
        "svg": "statics/axlUSDT.svg"
      },
      "denom": "axlUSDT",
      "channel": "channel-21",
      "minCoinDenom": "uusdt",
      "cosmosDenom": "ibc/F11C8CB7743E4B5FDCEA7C97F3B2C115E1931C5614B84C183DAC439B4C919D94",
      "category": "stablecoin",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xe01C6D4987Fc8dCE22988DADa92d56dA701d0Fe0",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "Wrapped Bitcoin on Axelar",
      "description": "Wrapped Bitcoin on Axelar",
      "images": {
        "png": "statics/axlWBTC.png"
      },
      "denom": "axlWBTC",
      "channel": "channel-21",
      "minCoinDenom": "wbtc-satoshi",
      "cosmosDenom": "ibc/C834CD421B4FD910BBC97E06E86B5E6F64EA2FE36D6AE0E4304C2E1FB1E7333C",
      "category": "bitcoin",
      "type": "IBC",
      "decimals": 8,
      "erc20Address": "0xF5b24c0093b65408ACE53df7ce86a02448d53b25",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "Wrapped Ether on Axelar",
      "description": "Wrapped Ether on Axelar",
      "images": {
        "png": "statics/axlWETH.png"
      },
      "denom": "axlWETH",
      "channel": "channel-21",
      "minCoinDenom": "weth-wei",
      "cosmosDenom": "ibc/356EDE917394B2AEF7F915EB24FA683A0CCB8D16DD4ECCEDC2AD0CEC6B66AC81",
      "category": "ethereum",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x50dE24B3f0B3136C50FA8A3B8ebc8BD80a269ce5",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    },
    {
      "name": "Lido staked ETH by Axelar",
      "description": "Lido staking derivative wstETH for staked ETH on Axelar",
      "images": {
        "png": "statics/axlWSTETH.png",
        "svg": "statics/axlWSTETH.png"
      },
      "denom": "axlWSTETH",
      "channel": "channel-21",
      "minCoinDenom": "wsteth-wei",
      "cosmosDenom": "ibc/43BD3A576550CDCD183BC093AEB610B3C2057AD12BA3C27D67AE9F4BCA74F2C8",
      "category": "ethereum",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0xA2A4B12EF81E7A26C5a1E0be9340b1972F85E44A",
      "handledByExternalUI": [
        {
          "url": "https://satellite.money/",
          "handlingAction": "Deposit and Withdraw"
        }
      ]
    }
  ],
  "clientId": "07-tendermint-69",
  "source": {
    "sourceChannel": "channel-22",
    "destinationChannel": "channel-21",
    "sourceIBCDenomToEvmos": "ibc/73D370D177CC659EA123B423D1AC194F0733537E5A346ECEA1DCBC8FEBB45FD3",
    "tendermintRest": {
      "http": [
        "https://axelar-mainnet-rpc.allthatnode.com:26657"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://lcd-axelar.imperator.co:443",
      "https://axelar-lcd.quickapi.com:443",
      "https://axelar-rest.chainode.tech:443",
      "https://axelar-lcd.qubelabs.io:443",
      "https://api-1.axelar.nodes.guru:443",
      "https://api-axelar-ia.cosmosia.notional.ventures/",
      "https://axelar-api.polkachu.com"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://axelar-grpc.quantnode.tech:9090"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://rpc-axelar.imperator.co:443",
      "https://axelar-rpc.quickapi.com:443",
      "https://axelar-rpc.chainode.tech:443",
      "https://axelar-rpc.pops.one:443",
      "https://axelar-rpc.qubelabs.io:443",
      "https://rpc-1.axelar.nodes.guru:443",
      "https://rpc-axelar-ia.cosmosia.notional.ventures/",
      "https://axelar-rpc.polkachu.com"
    ]
  }
} as const;