/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "comdex",
  "name": "Comdex",
  "cosmosId": "comdex-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "feeToken": "ucmdx",
  "currencies": [
    {
      "name": "Comdex",
      "description": "The native token of Comdex",
      "images": {
        "png": "statics/CMDX.png",
        "svg": "statics/CMDX.svg"
      },
      "denom": "CMDX",
      "channel": "channel-26",
      "sourcePrefix": "comdex",
      "baseDenom": "ucmdx",
      "minCoinDenom": "ucmdx",
      "cosmosDenom": "ibc/61DF64ADF65230540C14C63D64897BE08A3DC9A516A91425913F01240E2F432F",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xF0965c8f0755CF080a61C91EDd6707F0532c8fE7"
    },
    {
      "name": "CMST Stablecoin of Harbor protocol",
      "description": "An over-collateralized soft-pegged token to the USD on the Comdex chain",
      "images": {
        "png": "statics/CMST.png",
        "svg": "statics/CMST.svg"
      },
      "denom": "CMST",
      "channel": "channel-26",
      "sourcePrefix": "comdex",
      "baseDenom": "ucmst",
      "minCoinDenom": "ucmst",
      "cosmosDenom": "ibc/9EC8A1701813BB7B73BFED2496009ABB2C8BF187E6CDFA788D77F68E08BC05CD",
      "category": "stablecoin",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x9d6F2a9fDB32708e1AC07788cc29D6125ac73027"
    }
  ],
  "clientId": "07-tendermint-79",
  "source": {
    "sourceChannel": "channel-35",
    "destinationChannel": "channel-26",
    "sourceIBCDenomToEvmos": "ibc/D01562AB9C4CC84E06A84FFA213C7592508120C3F91EFFB1E62117D5932C2B1F",
    "tendermintRest": {
      "http": [
        "https://rpc.comdex.one"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://rest.comdex.one",
      "https://comdex-api.polkachu.com",
      "https://api-comdex-ia.cosmosia.notional.ventures",
      "https://comdex.mainnet.lcd.autostake.net",
      "https://comdex-api.lavenderfive.com",
      "https://api.comdex.chaintools.tech",
      "https://api-comdex.zenchainlabs.io"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://rpc.comdex.one"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://rpc.comdex.one",
      "https://comdex-rpc.polkachu.com",
      "https://rpc-comdex.zenchainlabs.io",
      "https://rpc-comdex-ia.cosmosia.notional.ventures",
      "https://comdex-rpc.lavenderfive.com",
      "https://rpc.comdex.chaintools.tech"
    ]
  }
} as const;