/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "cosmos",
  "name": "Cosmos Hub",
  "cosmosId": "cosmoshub-4",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "feeToken": "uatom",
  "currencies": [
    {
      "name": "Cosmos Hub",
      "description": "The native token of Cosmos Hub",
      "images": {
        "png": "statics/ATOM.png",
        "svg": "statics/ATOM.svg"
      },
      "denom": "ATOM",
      "channel": "channel-3",
      "sourcePrefix": "cosmos",
      "baseDenom": "uatom",
      "minCoinDenom": "uatom",
      "cosmosDenom": "ibc/A4DB47A9D3CF9A068D454513891B526702455D3EF08FB9EB558C561F9DC2B701",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xC5e00D3b04563950941f7137B5AfA3a534F0D6d6"
    }
  ],
  "clientId": "07-tendermint-3",
  "source": {
    "sourceChannel": "channel-292",
    "destinationChannel": "channel-3",
    "sourceIBCDenomToEvmos": "ibc/19DD710119533524061885A6F190B18AF28D9537E2BAE37F32A62C1A25979287",
    "tendermintRest": {
      "http": [
        "https://cosmoshub-rpc.stakely.io/"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://cosmos-lcd.quickapi.com:443",
      "https://lcd-cosmoshub.whispernode.com",
      "https://lcd-cosmoshub.blockapsis.com",
      "https://rest-cosmoshub.ecostake.com",
      "https://api.cosmoshub.pupmos.network",
      "https://lcd.cosmos.ezstaking.io",
      "https://api-cosmoshub-ia.notional.ventures/"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://cosmoshub-rpc.stakely.io/"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://cosmos-rpc.quickapi.com:443",
      "https://rpc-cosmoshub.whispernode.com",
      "https://rpc-cosmoshub.blockapsis.com",
      "https://cosmoshub.validator.network/",
      "https://rpc.cosmoshub.strange.love",
      "https://rpc.cosmos.network:443",
      "https://rpc-cosmoshub.ecostake.com",
      "https://rpc.cosmoshub.pupmos.network",
      "https://cosmos-rpc.polkachu.com",
      "https://rpc.cosmos.ezstaking.io",
      "https://rpc-cosmoshub-ia.notional.ventures/"
    ]
  }
} as const;