/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "cre",
  "name": "Crescent NetWork",
  "cosmosId": "crescent-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "feeToken": "ucre",
  "currencies": [
    {
      "name": "Crescent Network",
      "description": "The native token of Crecent Network",
      "images": {
        "png": "statics/CRE.png",
        "svg": "statics/CRE.svg"
      },
      "denom": "CRE",
      "channel": "channel-11",
      "sourcePrefix": "cre",
      "baseDenom": "ucre",
      "minCoinDenom": "ucre",
      "cosmosDenom": "ibc/B5AB26FB63C08E1C14B91B4DDC15CA4FE59737052B4432D8A3B328B66F6FE7A1",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x628A41754edfAFB491FEe6a1F397590B9013E01B"
    }
  ],
  "clientId": "07-tendermint-38",
  "source": {
    "sourceChannel": "channel-7",
    "destinationChannel": "channel-11",
    "sourceIBCDenomToEvmos": "ibc/73E97EB411B29C6F989C35D277D1A7FC65083572F102AC6BD101884EE9FB2C9F",
    "tendermintRest": {
      "http": [
        "https://mainnet.crescent.network:26657/"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://mainnet.crescent.network:1317",
      "https://api-crescent.pupmos.network",
      "https://crescent-api.polkachu.com",
      "https://crescent.rest.stakin-nodes.com",
      "https://crescent-mainnet-lcd.autostake.net:443"
    ]
  },
  "cosmosGRPC": null,
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://mainnet.crescent.network:26657",
      "https://crescent-rpc.polkachu.com",
      "https://rpc-crescent.pupmos.network",
      "https://crescent.rpc.stakin-nodes.com",
      "https://crescent-mainnet-rpc.autostake.net:443"
    ]
  }
} as const;