/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "emoney",
  "name": "EMoney",
  "cosmosId": "emoney-3",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "nativeCurrency": "EEUR",
  "currencies": [
    {
      "name": "e-Money EUR",
      "description": "e-Money EUR stablecoin",
      "images": {
        "png": "statics/EEUR.png",
        "svg": "statics/EEUR.svg"
      },
      "denom": "EEUR",
      "minCoinDenom": "eeur",
      "cosmosDenom": "ibc/AB40F54CC4BAF9C4FDB5CB5BDFC4D6CDB475BFE84BCEAF4F72F02EDAEED60F05",
      "category": "stablecoin",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x5db67696C3c088DfBf588d3dd849f44266ff0ffa"
    }
  ],
  "clientId": "07-tendermint-75",
  "cosmosRest": {
    "http": [
      "https://lcd-emoney.keplr.app",
      "https://emoney.validator.network/api",
      "https://api-emoney-ia.cosmosia.notional.ventures",
      "https://api.emoney.freak12techno.io",
      "https://e-money-api.ibs.team",
      "https://api.emoney.bh.rocks"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://rpc-emoney.keplr.app"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://rpc-emoney.keplr.app",
      "https://emoney.validator.network",
      "https://rpc.emoney.badgerbite.xyz:443",
      "https://rpc-emoney-ia.cosmosia.notional.ventures",
      "https://rpc.emoney.freak12techno.io",
      "https://e-money-rpc.ibs.team",
      "https://rpc-emoney.goldenratiostaking.net",
      "https://rpc.emoney.bh.rocks"
    ]
  }
} as const;