/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "gravity",
  "name": "Gravity Bridge",
  "cosmosId": "gravity-bridge-3",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.000",
    "average": "0.000",
    "high": "0.035"
  },
  "feeToken": "ugraviton",
  "currencies": [
    {
      "name": "Graviton",
      "description": "The native token of Gravity Bridge",
      "images": {
        "png": "statics/GRAV.png",
        "svg": "statics/GRAV.svg"
      },
      "denom": "GRAV",
      "channel": "channel-8",
      "sourcePrefix": "gravity",
      "baseDenom": "ugraviton",
      "minCoinDenom": "ugraviton",
      "cosmosDenom": "ibc/7F0C2CB6E79CC36D29DA7592899F98E3BEFD2CF77A94340C317032A78812393D",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd"
    },
    {
      "name": "USD Coin",
      "description": "USD Coin via Gravity Bridge",
      "images": {
        "png": "statics/USDC.grv.png"
      },
      "denom": "USDC.grv",
      "channel": "channel-8",
      "sourcePrefix": "gravity",
      "baseDenom": "uusdc",
      "minCoinDenom": "uusdc",
      "cosmosDenom": "ibc/693989F95CF3279ADC113A6EF21B02A51EC054C95A9083F2E290126668149433",
      "category": "stablecoin",
      "type": "ERC20",
      "decimals": 6,
      "erc20Address": "0x5FD55A1B9FC24967C4dB09C513C3BA0DFa7FF687"
    },
    {
      "name": "Dai Stablecoin",
      "description": "Dai Stablecoin via Gravity Bridge",
      "images": {
        "png": "statics/gDAI.png"
      },
      "denom": "gDAI",
      "channel": "channel-8",
      "sourcePrefix": "gravity",
      "baseDenom": "dai-wei",
      "minCoinDenom": "dai-wei",
      "cosmosDenom": "ibc/F96A7F81E8F82E4EE81F94D507CD257319EFB70FE46E23B4953F63B62E855603",
      "category": "stablecoin",
      "type": "ERC20",
      "decimals": 18,
      "erc20Address": "0xd567B3d7B8FE3C79a1AD8dA978812cfC4Fa05e75"
    },
    {
      "name": "Tether USD",
      "description": "Tether USD via Gravity Bridge",
      "images": {
        "png": "statics/gUSDT.png"
      },
      "denom": "gUSDT",
      "channel": "channel-8",
      "sourcePrefix": "gravity",
      "baseDenom": "uusdt",
      "minCoinDenom": "uusdt",
      "cosmosDenom": "ibc/DF63978F803A2E27CA5CC9B7631654CCF0BBC788B3B7F0A10200508E37C70992",
      "category": "stablecoin",
      "type": "ERC20",
      "decimals": 6,
      "erc20Address": "0xecEEEfCEE421D8062EF8d6b4D814efe4dc898265"
    },
    {
      "name": "Wrapped Bitcoin",
      "description": "Wrapped Bitcoin via Gravity Bridge",
      "images": {
        "png": "statics/gWBTC.png"
      },
      "denom": "gWBTC",
      "channel": "channel-8",
      "sourcePrefix": "gravity",
      "baseDenom": "satoshi",
      "minCoinDenom": "satoshi",
      "cosmosDenom": "ibc/350B6DC0FF48E3BDB856F40A8259909E484259ED452B3F4F39A0FEF874F30F61",
      "category": "bitcoin",
      "type": "ERC20",
      "decimals": 8,
      "erc20Address": "0x1D54EcB8583Ca25895c512A8308389fFD581F9c9"
    },
    {
      "name": "Wrapped Ether",
      "description": "Wrapped Ether via Gravity Bridge",
      "images": {
        "png": "statics/gWETH.png"
      },
      "denom": "gWETH",
      "channel": "channel-8",
      "sourcePrefix": "gravity",
      "baseDenom": "wei",
      "minCoinDenom": "wei",
      "cosmosDenom": "ibc/6B3FCE336C3465D3B72F7EFB4EB92FC521BC480FE9653F627A0BD0237DF213F3",
      "category": "ethereum",
      "type": "ERC20",
      "decimals": 18,
      "erc20Address": "0xc03345448969Dd8C00e9E4A85d2d9722d093aF8E"
    }
  ],
  "clientId": "07-tendermint-3",
  "source": {
    "sourceChannel": "channel-65",
    "destinationChannel": "channel-8",
    "sourceIBCDenomToEvmos": "ibc/6B207CDA2448604B83A0674AADD830C490C1AAB7D568135E52589E96A00B6EEF",
    "tendermintRest": {
      "http": [
        "https://gravitychain.io:26657/"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://gravitychain.io:1317",
      "https://lcd.gravity-bridge.ezstaking.io",
      "https://api-gravitybridge-ia.notional.ventures",
      "https://api.gravity-bridge.nodestake.top"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://lcd-gravity-bridge.keplr.app:9090/"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://gravitychain.io:26657",
      "http://gravity-bridge-1-08.nodes.amhost.net:26657",
      "https://gravity-rpc.polkachu.com",
      "https://rpc.gravity-bridge.ezstaking.io",
      "https://rpc-gravitybridge-ia.notional.ventures",
      "https://rpc.gravity-bridge.nodestake.top"
    ]
  }
} as const;