/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "inj",
  "name": "Injective",
  "cosmosId": "injective-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "100000000000",
    "average": "200000000000",
    "high": "30000000000000"
  },
  "nativeCurrency": "INJ",
  "currencies": [
    {
      "name": "Injective",
      "description": "The INJ token is the native governance token for the Injective chain.",
      "images": {
        "png": "statics/INJ.png"
      },
      "denom": "INJ",
      "channel": "channel-10",
      "minCoinDenom": "inj",
      "cosmosDenom": "ibc/ADF401C952ADD9EE232D52C8303B8BE17FE7953C8D420F20769AF77240BD0C58",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x3515F25AB7637adcF1b69F4D384ed5936B83431F"
    }
  ],
  "clientId": "07-tendermint-19",
  "source": {
    "sourceChannel": "channel-83",
    "destinationChannel": "channel-10",
    "sourceIBCDenomToEvmos": "ibc/16618B7F7AC551F48C057A13F4CA5503693FBFF507719A85BC6876B8BD75F821",
    "tendermintRest": {
      "http": [
        "https://tm.injective.network"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://lcd.injective.network",
      "https://injective-api.polkachu.com",
      "https://injective-api.lavenderfive.com:443"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://tm.injective.network"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://tm.injective.network",
      "https://injective-rpc.polkachu.com",
      "https://injective-rpc.quickapi.com:443"
    ]
  }
} as const;