/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "juno",
  "name": "Juno",
  "cosmosId": "juno-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.03",
    "average": "0.04",
    "high": "0.05"
  },
  "nativeCurrency": "JUNO",
  "currencies": [
    {
      "name": "Juno",
      "description": "The native token of Juno Network",
      "images": {
        "png": "statics/JUNO.png",
        "svg": "statics/JUNO.svg"
      },
      "denom": "JUNO",
      "channel": "channel-5",
      "minCoinDenom": "ujuno",
      "cosmosDenom": "ibc/448C1061CE97D86CC5E86374CD914870FB8EBA16C58661B5F1D3F46729A2422D",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x3452e23F9c4cC62c70B7ADAd699B264AF3549C19"
    }
  ],
  "clientId": "07-tendermint-14",
  "source": {
    "sourceChannel": "channel-70",
    "destinationChannel": "channel-5",
    "sourceIBCDenomToEvmos": "ibc/9B990F95D85E7CA8C46544975776CAA20A3DEE3507EEA829A4000D8D65617F6D",
    "tendermintRest": {
      "http": [
        "https://rpc-juno.whispernode.com"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://lcd-juno.itastakers.com",
      "https://rest-juno.ecostake.com",
      "https://juno-api.lavenderfive.com:443",
      "https://api.juno.pupmos.network",
      "https://api-juno-ia.cosmosia.notional.ventures",
      "https://juno-api.polkachu.com"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://rpc-juno.whispernode.com"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://rpc-juno.itastakers.com",
      "https://rpc-juno.ecostake.com",
      "https://juno-rpc.polkachu.com",
      "https://juno-rpc.lavenderfive.com:443",
      "https://rpc-juno-ia.cosmosia.notional.ventures",
      "https://rpc.juno.chaintools.tech",
      "https://rpc.juno.pupmos.network"
    ]
  }
} as const;