/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "osmo",
  "name": "Osmosis",
  "cosmosId": "osmosis-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "nativeCurrency": "OSMO",
  "currencies": [
    {
      "name": "Osmosis",
      "description": "The native token of Osmosis",
      "images": {
        "png": "statics/OSMO.png",
        "svg": "statics/OSMO.svg"
      },
      "denom": "OSMO",
      "minCoinDenom": "uosmo",
      "cosmosDenom": "ibc/ED07A3391A112B175915CD8FAF43A2DA8E4790EDE12566649D0C2F97716B8518",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xFA3C22C069B9556A4B2f7EcE1Ee3B467909f4864"
    }
  ],
  "clientId": "07-tendermint-0",
  "cosmosRest": {
    "http": [
      "https://osmosis-lcd.quickapi.com:443",
      "https://lcd-osmosis.whispernode.com",
      "https://lcd-osmosis.blockapsis.com",
      "https://rest-osmosis.ecostake.com",
      "https://api-osmosis-ia.notional.ventures",
      "https://lcd.osmosis.zone",
      "https://api.osmosis.interbloc.org"
    ]
  },
  "cosmosGRPC": null,
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://osmosis-rpc.quickapi.com:443",
      "https://rpc-osmosis.whispernode.com",
      "https://osmosis.validator.network",
      "https://rpc-osmosis.blockapsis.com",
      "https://rpc-osmosis.ecostake.com",
      "https://osmosis-rpc.polkachu.com",
      "https://rpc-osmosis-ia.notional.ventures",
      "https://rpc.osmosis.zone",
      "https://rpc.osmosis.interbloc.org"
    ]
  }
} as const;