/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "quick",
  "name": "quicksilver",
  "cosmosId": "quicksilver-2",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "nativeCurrency": "QCK",
  "currencies": [
    {
      "name": "Quicksilver",
      "description": "QCK - native token of Quicksilver",
      "images": {
        "png": "statics/QCK.png",
        "svg": "statics/QCK.svg"
      },
      "denom": "QCK",
      "channel": "channel-37",
      "minCoinDenom": "uqck",
      "cosmosDenom": "ibc/FCA18B0C0D1236E203D1AE09634A3F33E8AC31707CD59A74A437A903231C653C",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xf55454383cEEFB1B5e889E59542352B1b928707d"
    },
    {
      "name": "Quicksilver Liquid Staked ATOM",
      "description": "Quicksilver Liquid Staked ATOM",
      "images": {
        "png": "statics/qATOM.png",
        "svg": "statics/qATOM.svg"
      },
      "denom": "qATOM",
      "channel": "channel-37",
      "minCoinDenom": "uqatom",
      "cosmosDenom": "ibc/28F9F0420534AE42F7D220B04518A3A45A7F40A0855A1C353CB4BB7223A70F5A",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x4ad26064831ECE180B179a4C02Dc97940AA77B17"
    },
    {
      "name": "Quicksilver Liquid Staked OSMO",
      "description": "Quicksilver Liquid Staked OSMO",
      "images": {
        "png": "statics/qOSMO.png",
        "svg": "statics/qOSMO.svg"
      },
      "denom": "qOSMO",
      "channel": "channel-37",
      "minCoinDenom": "uqosmo",
      "cosmosDenom": "ibc/6230C2923C20C318C1002CE04856118621FE2A220F99EBA0EC2066D5DDFF2152",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x616E00909730f7dE9Afd97Dc71981f6d28e2B0ca"
    }
  ],
  "clientId": "07-tendermint-92",
  "source": {
    "sourceChannel": "channel-7",
    "destinationChannel": "channel-37",
    "sourceIBCDenomToEvmos": "ibc/73E97EB411B29C6F989C35D277D1A7FC65083572F102AC6BD101884EE9FB2C9F",
    "tendermintRest": {
      "http": [
        "https://quicksilver-rpc.polkachu.com:443"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://quicksilver-api.polkachu.com",
      "https://quicksilver-api.lavenderfive.com",
      "https://axelar-lcd.quickapi.com:443"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://quicksilver-rpc.polkachu.com:443"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://quicksilver-rpc.polkachu.com",
      "https://quicksilver-rpc.lavenderfive.com",
      "https://axelar-rpc.quickapi.com:443"
    ]
  }
} as const;