/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "regen",
  "name": "Regen Network",
  "cosmosId": "regen-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "nativeCurrency": "REGEN",
  "currencies": [
    {
      "name": "Regen Network",
      "description": "REGEN coin is the token for the Regen Network Platform",
      "images": {
        "png": "statics/REGEN.png"
      },
      "denom": "REGEN",
      "minCoinDenom": "uregen",
      "cosmosDenom": "ibc/36DCDCDFB1D0D723546878E241BC5800D27214E1E1DA31A4E424DE2280B0B0EE",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x0CE35b0D42608Ca54Eb7bcc8044f7087C18E7717"
    }
  ],
  "clientId": "07-tendermint-67",
  "cosmosRest": {
    "http": [
      "https://rest-regen.ecostake.com",
      "http://public-rpc.regen.vitwit.com:1317",
      "https://regen.stakesystems.io",
      "https://api-regen-ia.cosmosia.notional.ventures"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://rpc-regen.ecostake.com"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://rpc-regen.ecostake.com",
      "http://public-rpc.regen.vitwit.com:26657",
      "https://regen.stakesystems.io:2053",
      "http://rpc.regen.forbole.com:80",
      "https://rpc-regen-ia.cosmosia.notional.ventures"
    ]
  }
} as const;