/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "stars",
  "name": "Stargaze",
  "cosmosId": "stargaze-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "feeToken": "ustars",
  "currencies": [
    {
      "name": "Stargaze",
      "description": "The native token of Stargaze",
      "images": {
        "png": "statics/STARS.png"
      },
      "denom": "STARS",
      "channel": "channel-13",
      "sourcePrefix": "stars",
      "baseDenom": "ustars",
      "minCoinDenom": "ustars",
      "cosmosDenom": "ibc/7564B7F838579DD4517A225978C623504F852A6D0FF7984AFB28F10D36022BE8",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x5aD523d94Efb56C400941eb6F34393b84c75ba39"
    }
  ],
  "clientId": "07-tendermint-41",
  "source": {
    "sourceChannel": "channel-46",
    "destinationChannel": "channel-13",
    "sourceIBCDenomToEvmos": "ibc/F9C792DF71F960BB9EF698493B61E29C1EBB8FCD56B1F8BB08C86871F5F497C0",
    "tendermintRest": {
      "http": [
        "stargaze-grpc.polkachu.com:13790"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://rest.stargaze-apis.com",
      "https://api-stargaze.ezstaking.dev",
      "https://api-stargaze-ia.cosmosia.notional.ventures",
      "https://stargaze-api.ibs.team",
      "https://api-stargaze.d-stake.xyz",
      "https://api.stargaze.silentvalidator.com"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://rpc.stargaze-apis.com/",
      "https://rpc-stargaze.pupmos.network",
      "https://rpc-stargaze.ezstaking.dev"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://rpc.stargaze-apis.com",
      "https://rpc-stargaze.ezstaking.dev",
      "https://rpc-stargaze-ia.cosmosia.notional.ventures",
      "https://stargaze-rpc.ibs.team",
      "https://rpc-stargaze.d-stake.xyz",
      "https://rpc.stargaze.silentvalidator.com"
    ]
  }
} as const;