/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "stride",
  "name": "stride",
  "cosmosId": "stride-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "nativeCurrency": "STRD",
  "currencies": [
    {
      "name": "Stride",
      "description": "The native token of Stride",
      "images": {
        "png": "statics/STRD.png",
        "svg": "statics/STRD.svg"
      },
      "denom": "STRD",
      "channel": "channel-25",
      "minCoinDenom": "ustrd",
      "cosmosDenom": "ibc/21C0C3E238D48E370841635ADC3322F5D3D26342679102D5865DA8A56BD9524E",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x8FA78CEB7F04118Ec6d06AaC37Ca854691d8e963"
    },
    {
      "name": "Stride Staked Atom",
      "description": "Staking derivative by Stride",
      "images": {
        "png": "statics/stATOM.png",
        "svg": "statics/stATOM.svg"
      },
      "denom": "stATOM",
      "channel": "channel-25",
      "minCoinDenom": "stuatom",
      "cosmosDenom": "ibc/0830AFFC2F4F7CD24F9CEC07024FEA64CE3C5ABBC520DBD803BFA97BC3DCCA85",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xB5124FA2b2cF92B2D469b249433BA1c96BDF536D"
    },
    {
      "name": "Stride Staked Evmos",
      "description": "Staking derivative by Stride",
      "images": {
        "png": "statics/stEVMOS.png",
        "svg": "statics/stEVMOS.svg"
      },
      "denom": "stEVMOS",
      "channel": "channel-25",
      "minCoinDenom": "staevmos",
      "cosmosDenom": "ibc/C49FDA9CB980D813492E2DFFF255B01C46E629C73B2B468131F6FE6E14F55754",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x2C68D1d6aB986Ff4640b51e1F14C716a076E44C4"
    },
    {
      "name": "Stride Staked Inj",
      "description": "Staking derivative by Stride",
      "images": {
        "png": "statics/stINJ.png",
        "svg": "statics/stINJ.svg"
      },
      "denom": "stINJ",
      "channel": "channel-25",
      "minCoinDenom": "stinj",
      "cosmosDenom": "ibc/4FCDD6D71CAB4F6BBEAB781D036977E1158075297671345055BC342D46819640",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 18,
      "erc20Address": "0x786744d8B40ee154FA4a74153c4d33dF09aBf015"
    },
    {
      "name": "Stride Staked Juno",
      "description": "Staking derivative by Stride",
      "images": {
        "png": "statics/stJUNO.png",
        "svg": "statics/stJUNO.svg"
      },
      "denom": "stJUNO",
      "channel": "channel-25",
      "minCoinDenom": "stujuno",
      "cosmosDenom": "ibc/D9C9DFD2B4021D16B01AC16ECD5A7933383C38F8331160583E0A5F34B30E1BA9",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xc71aAf8e486e3F33841BB56Ca3FD2aC3fa8D29a8"
    },
    {
      "name": "Stride Staked Osmo",
      "description": "Staking derivative by Stride",
      "images": {
        "png": "statics/stOSMO.png",
        "svg": "statics/stOSMO.svg"
      },
      "denom": "stOSMO",
      "channel": "channel-25",
      "minCoinDenom": "stuosmo",
      "cosmosDenom": "ibc/C9364B2C453F0428D04FD40B6CF486BA138FA462FE43A116268A7B695AFCFE7F",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xD32eB974468ed767338533842D2D4Cc90B9BAb46"
    },
    {
      "name": "Stride Staked Stars",
      "description": "Staking derivative by Stride",
      "images": {
        "png": "statics/stSTARS.png",
        "svg": "statics/stSTARS.svg"
      },
      "denom": "stSTARS",
      "channel": "channel-25",
      "minCoinDenom": "stustars",
      "cosmosDenom": "ibc/1464C6BD4C7ADB0A15BE85F48EE1E04A5371F4727F609FBAB788CF5137FDAAB7",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0xc7e56EEc629D3728fE41baCa2f6BFc502096f94E"
    }
  ],
  "clientId": "07-tendermint-77",
  "source": {
    "sourceChannel": "channel-9",
    "destinationChannel": "channel-25",
    "sourceIBCDenomToEvmos": "ibc/A3643FAA80C7DA7E72B23853340F6EAD4F3A698CDC39CE42FBF23F3A4A6E3803",
    "tendermintRest": {
      "http": [
        "https://stride-rpc.polkachu.com:443"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://stride-api.polkachu.com",
      "https://stride.api.chandrastation.com",
      "https://api.stride.bh.rocks",
      "http://api-stride.nodeist.net",
      "https://stride-api.lavenderfive.com",
      "https://stride.rest.interchain.ivaldilabs.xyz",
      "https://api.stride.nodestake.top",
      "https://api-stride.d-stake.xyz"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://stride-rpc.polkachu.com:443"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://stride-rpc.polkachu.com",
      "https://stride.rpc.chandrastation.com",
      "https://rpc.stride.bh.rocks",
      "http://rpc-stride.nodeist.net",
      "https://stride-rpc.lavenderfive.com",
      "https://stride.rpc.interchain.ivaldilabs.xyz",
      "https://rpc.stride.nodestake.top",
      "https://rpc-stride.d-stake.xyz",
      "https://rpc.stride.silentvalidator.com",
      "https://stride.rpc.kjnodes.com"
    ]
  }
} as const;