/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "tori",
  "name": "teritori",
  "cosmosId": "teritori-1",
  "evmId": null,
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "feeToken": "utori",
  "currencies": [
    {
      "name": "Teritori",
      "description": "The native staking and governance token of the Teritori chain",
      "images": {
        "png": "statics/TORI.png"
      },
      "denom": "TORI",
      "channel": "channel-35",
      "sourcePrefix": "tori",
      "baseDenom": "utori",
      "minCoinDenom": "utori",
      "cosmosDenom": "ibc/18D5C3CDDF1DEE108CE4BF0A7E0262D94D11AB06A37F68EA38F70CC92C5D894F",
      "category": "cosmos",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x205CF44075E77A3543abC690437F3b2819bc450a"
    }
  ],
  "clientId": "07-tendermint-89",
  "source": {
    "sourceChannel": "channel-1",
    "destinationChannel": "channel-35",
    "sourceIBCDenomToEvmos": "ibc/6993F2B27985C9363D3B94D702111940055833A2BA86DA93F33A67D03E4D1B7D",
    "tendermintRest": {
      "http": [
        "https://rpc.mainnet.teritori.com"
      ]
    }
  },
  "cosmosRest": {
    "http": [
      "https://teritori-api.lavenderfive.com:443",
      "https://teritori-api.polkachu.com",
      "https://api-teritori.nodeist.net",
      "https://api.teritori.nodestake.top",
      "https://rest.mainnet.teritori.com"
    ]
  },
  "cosmosGRPC": {
    "http": [
      "https://rpc.mainnet.teritori.com"
    ]
  },
  "evmRest": null,
  "tendermint": {
    "http": [
      "https://teritori-rpc.lavenderfive.com:443",
      "https://teritori-rpc.polkachu.com",
      "https://rpc-teritori.nodeist.net",
      "https://rpc.teritori.nodestake.top",
      "https://teritori.nodejumper.io"
    ]
  }
} as const;