name: E2E Tests
on:
  push:
    branches: [main, production]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, production]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v6.0.1
        id: git_diff
        with:
          PATTERNS: |
            **/*.js
            **/*.jsx
            **/*.json
            **/*.ts
            **/*.tsx

      - name: Install modules
        run: yarn install
        if: env.GIT_DIFF

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Build
        run: yarn run build

      - name: Run tests
        run: xvfb-run yarn test:e2e
        if: env.GIT_DIFF
