name: Test
on:
  push:
    branches: [main, production]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, production]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

        # Build required
        # https://stackoverflow.com/questions/69110913/within-in-a-monorepo-is-it-possible-to-configure-a-package-to-use-the-uncompil
      - name: Run Build
        run: yarn run build

      - uses: technote-space/get-diff-action@v6.0.1
        id: git_diff
        with:
          PATTERNS: |
            **/*.js
            **/*.jsx
            **/*.json
            **/*.ts
            **/*.tsx

      - name: Install modules
        run: yarn install
        if: env.GIT_DIFF

      - name: Run tests
        run: yarn test:coverage
        if: env.GIT_DIFF
